### ISSUE TITLE
Prep Meeting Agenda

### ISSUE THREAD

**Issue by raveling** [avelingrayorg/cc-pm#11]

**Comment by raveling** [comment]
Can we schedule a time to get together to get our pitch congealed and gluey?

How about your Friday afternoon @bobbymray  ?

**Comment by bobbymray** [comment]
My Friday afternoon is a good time to get together. See you then.

**Comment by raveling** [comment]
Perfect

**Comment by raveling** [comment]
@bobbymray 

"Build Options" Doc has been uploaded to the repo:

https://github.com/avelingrayorg/cc-pm/blob/master/DOCS/Build-Options.md

**Comment by raveling** [comment]
@bobbymray I did a second pass on the doc

(see last two commits)

Take a look now, and if you have any changes in mind, just make them and push.
I'm going to be out for most of today, but would like to send this out before our meeting.
So I can send at the end of my day once you have had a chance to peruse.

**Comment by bobbymray** [comment]
@raveling I'm done

**Comment by raveling** [comment]
@bobbymray great stuff, thanks!
closed #11

**Comment by raveling** [comment]
closing #11
