### ISSUE TITLE
Assess Viability of Squarespace Store

### ISSUE THREAD

**Issue by raveling** [avelingrayorg/cc-pm#12]

**Comment by raveling** [comment]
@bobbymray I've had a 15 minute look into the store option with SS. 
Without going all the way into setting up a proxy site, it looks to me like irrespective of the plan, you need to pick a template that supports products.
Then, depending on what plan you choose, you get a transaction fee of 3%, or 2%, or no fee (with the "Online Stores" pricing plans).
Not sure how much further we should go before  the mtg. Let me know if you want to dig deeper with some actual store mockups.

**Comment by bobbymray** [comment]
is the issue here the transaction fees? a mockup store isn't going to change the transaction fees. we should've given more info about transaction fees for both SS & Shopify in the Build Options. maybe should amend it with that info. personally don't want to take the time to mock up an SS

**Comment by bobbymray** [comment]
client chose Jekyll for the site
