### ISSUE TITLE
Client response for WP enquiry

### ISSUE THREAD

**Issue by raveling** [avelingrayorg/cc-pm#14]
Sivan wants to know why not WP?

**Comment by bobbymray** [comment]
Replied to Sivan's email on 1/24/17

1. the development time would be longer than any of the offered options
2. the maintenance obligations are much greater than for any of the offered options (plugin & core updates)
3. security is an ongoing issue with WordPress (WordPress sites are a favorite target of hackers) this relates to #2, as out-of-date plugins are a typical point of entry for hackers
