### ISSUE TITLE
Review CC's December documentation submissions and outline important discussion points.

### ISSUE THREAD

**Issue by raveling** [avelingrayorg/cc-pm#6]

**Comment by raveling** [comment]
@bobbymray please review and comment below when you can.

I reviewed all the documents to freshen up on things. It seems to me that the priority issues to lock down now are: 

## Logo
- Insufficient Funds in current budget

## Store
- Insufficient Funds in current budget
- Question about ROI for store venture - need more information about products and marketing efforts.
- Media Embeds (for audio e.g. bandcamp) can be an option that could be included as a possible _collection type if we use the jekyll CMS (?).
- PDFs could be farmed out for sale from elsewhere and we could add a button to buy
- Or Shopify as CMS if the $30/mo can be justified against sales potential.

## Videos
- Not yet provided by client.

## Media Assets
- We need to reaffirm stance on images. 
- Can offer deployment of CC licensed images provided attribution is included.

**Comment by bobbymray** [comment]
This looks good.
I wonder if we should ask her to elaborate on "immediate transformation" with regard to Marin Idol.
Also, is Simply Music the approach she offers to all piano students, or is there something exclusive about it?

**Comment by raveling** [comment]
> I wonder if we should ask her to elaborate on "immediate transformation" with regard to Marin Idol.

I say don't mention it at the mo.
We can deal with it in the content writing phase. Will probs just write something without it. 
:-)

**Comment by raveling** [comment]
I can write up a correspondence to C/S for this tomorrow if you like?
My gut tells me it would be good to send the ball back to their side of the court, and maybe then schedule a final pow-wow via Skype post xmas where we can cover any remaining tidbits?

**Comment by raveling** [comment]
Correspondence has been sent to CC/SG. 
Awaiting Response

**Comment by raveling** [comment]
Moving to Completed Status
